Some info'bout U
컴컴컴컴컴컴컴컴

           NAME:
      real name:
           born:
            sex:
            age:
           addr:
       net addr:
          voice:
        machine:
           line:
          loves:
          hates:
favourite music:
   ...languages:
        ...food:
      ...drinks:
  ...kinda girl:
      ...sports:
       ...games:
       ...books:
      ...movies:

<UCL application form by Me헳O. Partially remixed by SkullC0DEr>
